#!/bin/sh

set -e

for v in $(pg_buildext supported-versions); do
	mkdir -p build-$v
	test -L build-$v/sql || ln -s ../sql build-$v/
	test -L build-$v/expected || ln -s ../expected build-$v/

	pg_buildext installcheck-$v
done
